# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\x12\x05movie\"\x1b\n\x07MovieId\x12\x10\n\x08movie_id\x18\x01 \x01(\x05\"/\n\x0bMovieRating\x12\x10\n\x08movie_id\x18\x01 \x01(\x05\x12\x0e\n\x06rating\x18\x02 \x01(\x01\x32\xee\x01\n\x12MovieRatingService\x12\x35\n\tAddRating\x12\x12.movie.MovieRating\x1a\x12.movie.MovieRating\"\x00\x12\x31\n\tGetRating\x12\x0e.movie.MovieId\x1a\x12.movie.MovieRating\"\x00\x12\x38\n\x0cUpdateRating\x12\x12.movie.MovieRating\x1a\x12.movie.MovieRating\"\x00\x12\x34\n\x0c\x44\x65leteRating\x12\x0e.movie.MovieId\x1a\x12.movie.MovieRating\"\x00\x42\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _MOVIEID._serialized_start=22
  _MOVIEID._serialized_end=49
  _MOVIERATING._serialized_start=51
  _MOVIERATING._serialized_end=98
  _MOVIERATINGSERVICE._serialized_start=101
  _MOVIERATINGSERVICE._serialized_end=339
# @@protoc_insertion_point(module_scope)
